### ISSUE TITLE
Panic when route with `nil` handler matched

### ISSUE THREAD

**Issue by jakenichols2719** [decentplatforms/matcha#100]
If you use a registration call, like `Router.Handle`, and provide `nil` in place of a handler, Matcha panics when the given route is matched. While this is sort of an edge case, ideally Matcha wouldn't panic in most circumstances, and this is a very preventable one. So, to fix this issue:

- Determine where a registered `nil` handler is called
- Add a guard (`if handler != nil...`) and only call the handler if it isn't nil
- Determine an appropriate default response code if the handler is nil (no body)
- Test and document the new behavior

Please don't solve this issue by throwing an error if a user provides a nil handler; this is potentially valuable behavior since it lets users safely create placeholder routes to implement later.

**Comment by aritt0923** [comment]
I'd be happy to take a look at this one.

**Comment by jakenichols2719** [comment]
Closed as complete by #101. Thanks, @aritt0923!

**Comment by SuneelFreimuth** [comment]
While `nil` serving as a symbol for "todo" is reasonable, I don't see how it's preferrable to, say, `matcha.UnimplementedRoute`

**Comment by jakenichols2719** [comment]
@SuneelFreimuth It's not so much that it's preferable, it's that the current behavior of `nil` handlers (panic when route us matched) is undesirable. The ideal state for Matcha is one in which it _never_ panics, including when presented with conditions that don't necessarily make sense, like a nil handler. I actually really like your suggestion, but the specific goal was just to resolve the panic in an edge case, not to introduce new behavior. I actually call this out in the patch notes, IIRC.

I'm actually glad it came up because it was a great learning opportunity for myself and the contributor who fixed it--turns out that in some cases something can be `nil` but also not `nil`!
