### ISSUE TITLE
Alias common commands in a central package

### ISSUE THREAD

**Issue by jakenichols2719** [decentplatforms/matcha#103]
One of the big things I've noticed doing development with Matcha is that I have to import _lots_ of packages. Even more frustrating is that most of these packages have common names, like `router`, `route`, or `middleware`. This (especially that last one) has cause issues that are resolvable but annoying.

With the API and implementation stable for the past couple of months, I think it'd be a good idea to alias things like `router.New` in a central `matcha` package.

**Comment by jnichols-git** [comment]
Closed as complete by #110, but will keep an eye on this in the future for more additions
