### ISSUE TITLE
Mounted handlers don't have access to the full path of the request

### ISSUE THREAD

**Issue by jakenichols2719** [decentplatforms/matcha#104]
If you use `Router.Mount` to send all requests at a subroute to a handler, it doesn't have access to the full path of the request. This causes issues if you need to redirect back to the current location.

My suggestion is to add a field to `rctx` that holds the original URI of the request and treat it as a reserved parameter, like `fullpath`, that can only be set once per context. This introduces the concept of reserved parameters, which I think will be a nice extension to `rctx` that prevents an explosion of helper functions in that package.

**Comment by jnichols-git** [comment]
Closed as complete by #105
